# Generated by Django 3.2.16 on 2022-10-31 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='number_of_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
