# Generated by Django 3.2.16 on 2022-11-01 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_auto_20221031_2014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='number_of_guests',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='room',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
