# Generated by Django 3.2.16 on 2022-12-06 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_auto_20221101_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('passport', models.CharField(max_length=100)),
                ('Продолжительность', models.DurationField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='places.room')),
            ],
        ),
    ]
