# Generated by Django 3.2.16 on 2022-12-06 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_auto_20221206_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='first_day',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='last_day',
            field=models.DateTimeField(null=True),
        ),
    ]
