# Generated by Django 3.2.16 on 2022-12-06 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_auto_20221206_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='Продолжительность',
        ),
    ]
